[#175160851]Add VisibleServicePayload and InvisibleServicePayload definitions
pagopa/io-functions-commons pull request #114
Opened 2020-10-29 12:10 UTC by infantesimone

This PR introduces a new definition for `ServicePayload` in order to model the mandatory of service metadata for visible services.

So, the new `ServicePayload`  is valid against one of the following schema:

 - `VisibleServicePayload` 
 - `InvisibleServicePayload`

These definitions differ only for the metadata property, which in the case of `VisibleServicePayload` is required.

(The PR is draft because there are some possible error in model generation)

2020-10-29 12:13 UTC, gunzip commented on openapi/definitions.yaml
> +        enum: [ true ]
why not `default: true `?

2020-10-29 13:25 UTC, infantesimone commented
`oneOf` is not support from the swagger version 2.0

2020-10-29 13:28 UTC, gunzip commented
you can emulate it in italia-utils adding x-one-of

https://github.com/pagopa/io-utils/blob/1d05f9ca244bb628dc8123d4d3f4fbd44423e3e1/__mocks__/api.yaml#L167

2020-11-02 15:00 UTC, AleDore reviewed
Why draft?

2020-11-02 15:12 UTC, infantesimone commented
io-utils not support boolean with enum require from `VisibleServicePayload` and `InvisibleServicePayload` definitions, so after [this](https://github.com/pagopa/io-utils/pull/208)  I can conclude this PR.

2020-11-03 16:10 UTC, gunzip approved these changes
@balanza can we merge this?

2020-11-03 16:18 UTC, balanza requested changes
As we're touching definitions being consumed by other projects, I'd add some tests to be sure we're not introducing behavioural changes

2020-11-03 17:43 UTC, balanza approved these changes
very good 👍

2020-11-03 17:44 UTC, merged