[IOCOM-1047] Fix openapi for RC
pagopa/io-functions-commons pull request #364
Opened 2024-02-08 14:34 UTC by Garma00

#### List of Changes

* [Use FiscalCode for disableLollipopFor](https://github.com/pagopa/io-functions-commons/commit/e9ebf40d4232ecff3a24f1f73fea3d993e7fbc76);
* [Fix format of the description](https://github.com/pagopa/io-functions-commons/commit/1c6745995468c04105b305340e75a2fcfd3c4178);
* [Add new ulid generator that actually return a Ulid](https://github.com/pagopa/io-functions-commons/commit/8253a6f51afe0e8c0c4a9fb81370758f3bc72545)

#### Motivation and Context

Small changes needed for RC

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-08 15:22 UTC, michaeldisaro approved these changes

2024-02-08 15:46 UTC, michaeldisaro requested changes
we hae to fix the fact to build the model with the specs... specs shoudl be snake_cased, model must be defined inside de file without generator and have camelCased properties.

2024-02-09 13:49 UTC, acuiuli approved these changes
LGTM

2024-02-09 16:20 UTC, michaeldisaro requested changes

2024-02-09 16:20 UTC, michaeldisaro commented on src/utils/rc_configuration.ts
> +export const retrievedMessageToPublic = (
the name of the function is wrong :)

2024-02-09 18:15 UTC, michaeldisaro approved these changes

2024-02-12 09:13 UTC, merged